name: "deploy ecs code"
on:
  repository_dispatch:
    types: [code-deploy-ecs-event]
    branches: [main]
jobs:
  deploy-ecs:
    name: deploy ecs code
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    env:
      ENV: dev
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get the image URI
        id: build-push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: belcorp-0001-demo-fpm-${{ env.ENV }}-images-repository
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          echo "image=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" >> "$GITHUB_OUTPUT"

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition belcorp-0001-demo-fpm-${{ env.ENV }}-task-definition-for-dbt --query taskDefinition > task-definition.json
          dir
          cat task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: belcorp-0001-demo-fpm-${{ env.ENV }}-task-definition-for-dbt-container
          image: ${{ steps.build-push-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: belcorp-0001-demo-fpm-${{ env.ENV }}-demonet
          cluster: belcorp-0001-demo-fpm-${{ env.ENV }}-cluster-for-dbt
          wait-for-service-stability: true